services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.txt
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      - API_KEY=house-designer-secret

  frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  ports:
    - "3000:3000"
  environment:
    - NEXT_PUBLIC_API_URL=https://house-designer-hroi.onrender.com
  depends_on:
    - backend